[package]
name = "pepematrix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pepematrix"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.4"
numpy = "0.23.0"
ndarray = "0.16.1"
